- name: Cleanup
  # TODO: change to remote if you have one
  hosts: local
  become: true
  tasks:
    - name: Remove packages
      community.general.pacman:
        name: "{{ packages }}"
        state: absent

    - name: Stop {{ app_service }}
      ansible.builtin.systemd:
        name: "{{ app_service }}"
        state: stopped
        enabled: false

    - name: Remove {{ app_service }}
      ansible.builtin.file:
        path: /etc/systemd/system/{{ app_service }}
        state: absent

    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Force delete unit
      ansible.builtin.command: systemctl reset-failed {{ app_service }}
      register: reset_failed
      changed_when: "reset_failed.rc == 0"

    - name: Remove {{ app_dir }}/{{ app_file }}
      ansible.builtin.file:
        path: "{{ app_dir }}/{{ app_file }}"
        state: absent
